### ISSUE TITLE
Errors while building

### ISSUE THREAD

**Issue by YaKsss** [brobwind/pie-device-brobwind-rpi3#3]
Hi,
I followed all the indicated steps but I got an error after few minutes building the images. 

Full output below, here some extracts:

- Found class java.io.PrintWriter, but unable to insert @libcore.util.NonNull:
- FAILED: out/target/product/rpi3/gen/STATIC_LIBRARIES/libmesa_nir_intermediates
- Found class java.util.HashMap, but unable to insert @libcore.util.NullFromTypeParam:
- File "device/brobwind/rpi3/hals/display/mesa3d/src/compiler/nir/nir_opcodes_h.py", line 45, in <module>
    from mako.template import Template
ImportError: No module named mako.template
- [  4% 2936/61716] target thumb C: libext <= out/target/product/rpi3/obj/STATIC_LIBRARIES/libext_intermediates/libxt_tcp.c
ninja: build stopped: subcommand failed.

I got the sources from https://android.googlesource.com , could it be that the reason?

many thanks.

:~$ m -j
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
TARGET_PRODUCT=rpi3
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.15.0-45-generic-x86_64-Ubuntu-16.04.6-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PPR2.180905.006.A1
OUT_DIR=out

[1/1] out/soong/.minibootstrap/minibp out/soong/.bootstrap/build.ninja
[45/46] glob libcore/openjdk_java_files.bp
[77/77] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
out/build-rpi3-cleanspec.ninja is missing, regenerating...
out/build-rpi3.ninja is missing, regenerating...
[550/920] including system/sepolicy/Android.mk ...
system/sepolicy/Android.mk:79: warning: BOARD_SEPOLICY_VERS not specified, assuming current platform version
[920/920] including tools/tradefederation/core/Android.mk ...
build/make/core/Makefile:28: warning: overriding commands for target `out/target/product/rpi3/system/etc/mkshrc'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `out/target/product/rpi3/system/etc/mkshrc'
build/make/core/Makefile:28: warning: overriding commands for target `out/target/product/rpi3/system/etc/ld.config.28.txt'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `out/target/product/rpi3/system/etc/ld.config.28.txt'
build/make/core/Makefile:28: warning: overriding commands for target `out/target/product/rpi3/vendor/etc/wifi/wpa_supplicant.conf'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `out/target/product/rpi3/vendor/etc/wifi/wpa_supplicant.conf'
[ 99% 927/928] glob tools/tradefederation/core/atest/**/*.py
[  0% 154/61716] build out/target/product/rpi3/rpiboot.img
Target rpiboot fs image: out/target/product/rpi3/obj/PACKAGING/rpibootimage_intermediates/rpiboot.img
64+0 records in
64+0 records out
67108864 bytes (67 MB, 64 MiB) copied, 0.104174 s, 644 MB/s
mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
mkfs.fat 3.0.28 (2015-05-16)
Install rpiboot fs image: out/target/product/rpi3/rpiboot.img
[  1% 915/61716] build out/target/common/obj/JAVA_LIBRARIES/core-oj_intermediates/annotated/timestamp
WARNING: duplicate annotation of type libcore.util.NonNull
WARNING: duplicate annotation of type libcore.util.NonNull
Found class java.io.PrintWriter, but unable to insert @libcore.util.NonNull:
  @libcore.util.NonNull (nl=false) @ {GENERIC_ARRAY_LOCATION=GenericArrayLocationCriterion at outermost type, RETURN_TYPE=ReturnTypeCriterion for method: append(C)Ljava/io/Writer;, IN_METHOD=in method 'append(C)Ljava/io/Writer;', IN_CLASS=In class 'java.io.PrintWriter' (exactly)}
Found class java.io.PrintWriter, but unable to insert @libcore.util.NonNull:
  @libcore.util.NonNull (nl=false) @ {GENERIC_ARRAY_LOCATION=GenericArrayLocationCriterion at outermost type, RETURN_TYPE=ReturnTypeCriterion for method: append(C)Ljava/lang/Appendable;, IN_METHOD=in method 'append(C)Ljava/lang/Appendable;', IN_CLASS=In class 'java.io.PrintWriter' (exactly)}
Found class java.io.PrintWriter, but unable to insert @libcore.util.NonNull:
  @libcore.util.NonNull (nl=false) @ {GENERIC_ARRAY_LOCATION=GenericArrayLocationCriterion at outermost type, RETURN_TYPE=ReturnTypeCriterion for method: append(Ljava/lang/CharSequence;)Ljava/io/Writer;, IN_METHOD=in method 'append(Ljava/lang/CharSequence;)Ljava/io/Writer;', IN_CLASS=In class 'java.io.PrintWriter' (exactly)}
Found class java.io.PrintWriter, but unable to insert @libcore.util.Nullable:
  @libcore.util.Nullable (nl=false) @ {GENERIC_ARRAY_LOCATION=GenericArrayLocationCriterion at outermost type, PARAM=ParamCriterion for method: append(Ljava/lang/CharSequence;) at position: 0, IN_METHOD=in method 'append(Ljava/lang/CharSequence;)Ljava/io/Writer;', IN_CLASS=In class 'java.io.PrintWriter' (exactly)}
Found class java.io.PrintWriter, but unable to insert @libcore.util.NonNull:
  @libcore.util.NonNull (nl=false) @ {GENERIC_ARRAY_LOCATION=GenericArrayLocationCriterion at outermost type, RETURN_TYPE=ReturnTypeCriterion for method: append(Ljava/lang/CharSequence;)Ljava/lang/Appendable;, IN_METHOD=in method 'append(Ljava/lang/CharSequence;)Ljava/lang/Appendable;', IN_CLASS=In class 'java.io.PrintWriter' (exactly)}
Found class java.io.PrintWriter, but unable to insert @libcore.util.Nullable:
  @libcore.util.Nullable (nl=false) @ {GENERIC_ARRAY_LOCATION=GenericArrayLocationCriterion at outermost type, PARAM=ParamCriterion for method: append(Ljava/lang/CharSequence;) at position: 0, IN_METHOD=in method 'append(Ljava/lang/CharSequence;)Ljava/lang/Appendable;', IN_CLASS=In class 'java.io.PrintWriter' (exactly)}
Found class java.io.PrintWriter, but unable to insert @libcore.util.NonNull:
  @libcore.util.NonNull (nl=false) @ {GENERIC_ARRAY_LOCATION=GenericArrayLocationCriterion at outermost type, RETURN_TYPE=ReturnTypeCriterion for method: append(Ljava/lang/CharSequence;II)Ljava/io/Writer;, IN_METHOD=in method 'append(Ljava/lang/CharSequence;II)Ljava/io/Writer;', IN_CLASS=In class 'java.io.PrintWriter' (exactly)}
Found class java.io.PrintWriter, but unable to insert @libcore.util.Nullable:
  @libcore.util.Nullable (nl=false) @ {GENERIC_ARRAY_LOCATION=GenericArrayLocationCriterion at outermost type, PARAM=ParamCriterion for method: append(Ljava/lang/CharSequence;II) at position: 0, IN_METHOD=in method 'append(Ljava/lang/CharSequence;II)Ljava/io/Writer;', IN_CLASS=In class 'java.io.PrintWriter' (exactly)}
Found class java.io.PrintWriter, but unable to insert @libcore.util.NonNull:
  @libcore.util.NonNull (nl=false) @ {GENERIC_ARRAY_LOCATION=GenericArrayLocationCriterion at outermost type, RETURN_TYPE=ReturnTypeCriterion for method: append(Ljava/lang/CharSequence;II)Ljava/lang/Appendable;, IN_METHOD=in method 'append(Ljava/lang/CharSequence;II)Ljava/lang/Appendable;', IN_CLASS=In class 'java.io.PrintWriter' (exactly)}
Found class java.io.PrintWriter, but unable to insert @libcore.util.Nullable:
  @libcore.util.Nullable (nl=false) @ {GENERIC_ARRAY_LOCATION=GenericArrayLocationCriterion at outermost type, PARAM=ParamCriterion for method: append(Ljava/lang/CharSequence;II) at position: 0, IN_METHOD=in method 'append(Ljava/lang/CharSequence;II)Ljava/lang/Appendable;', IN_CLASS=In class 'java.io.PrintWriter' (exactly)}
Found class java.util.HashMap, but unable to insert @libcore.util.NonNull:
  @libcore.util.NonNull (nl=false) @ {GENERIC_ARRAY_LOCATION=GenericArrayLocationCriterion at ( [TYPE_ARGUMENT(0)] ), RETURN_TYPE=ReturnTypeCriterion for method: entrySet()Ljava/util/Set;, IN_METHOD=in method 'entrySet()Ljava/util/Set;', IN_CLASS=In class 'java.util.HashMap' (exactly)}
Found class java.util.HashMap, but unable to insert @libcore.util.NullFromTypeParam:
  @libcore.util.NullFromTypeParam (nl=false) @ {GENERIC_ARRAY_LOCATION=GenericArrayLocationCriterion at ( [TYPE_ARGUMENT(0), TYPE_ARGUMENT(0)] ), RETURN_TYPE=ReturnTypeCriterion for method: entrySet()Ljava/util/Set;, IN_METHOD=in method 'entrySet()Ljava/util/Set;', IN_CLASS=In class 'java.util.HashMap' (exactly)}
Found class java.util.HashMap, but unable to insert @libcore.util.NullFromTypeParam:
  @libcore.util.NullFromTypeParam (nl=false) @ {GENERIC_ARRAY_LOCATION=GenericArrayLocationCriterion at ( [TYPE_ARGUMENT(0), TYPE_ARGUMENT(1)] ), RETURN_TYPE=ReturnTypeCriterion for method: entrySet()Ljava/util/Set;, IN_METHOD=in method 'entrySet()Ljava/util/Set;', IN_CLASS=In class 'java.util.HashMap' (exactly)}
[  4% 2931/61716] build out/target/product/rpi3/gen/STATIC_LIBRARIES/libmesa_nir_intermediates/nir/nir_opcodes.h
FAILED: out/target/product/rpi3/gen/STATIC_LIBRARIES/libmesa_nir_intermediates/nir/nir_opcodes.h 
/bin/bash -c "python device/brobwind/rpi3/hals/display/mesa3d/src/compiler/nir/nir_opcodes_h.py device/brobwind/rpi3/hals/display/mesa3d/src/compiler/nir/nir_opcodes.py > out/target/product/rpi3/gen/STATIC_LIBRARIES/libmesa_nir_intermediates/nir/nir_opcodes.h"
Traceback (most recent call last):
  File "device/brobwind/rpi3/hals/display/mesa3d/src/compiler/nir/nir_opcodes_h.py", line 45, in <module>
    from mako.template import Template
ImportError: No module named mako.template
[  4% 2936/61716] target thumb C: libext <= out/target/product/rpi3/obj/STATIC_LIBRARIES/libext_intermediates/libxt_tcp.c
ninja: build stopped: subcommand failed.
19:24:58 ninja failed with: exit status 1

**Comment by YaKsss** [comment]
I can confirm that after installing some missing packages, the building process could be resumed :)
$ sudo apt-get install python-pip libyaml-dev
$ sudo pip install prettytable Mako pyaml dateutils --upgrade
