### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by snd-raspberry** [brobwind/pie-device-brobwind-rpi3#4]
Hi Brobwind,
I have a build failure:
mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
mkfs.fat 4.1 (2017-01-24)
Traceback (most recent call last):
  File "build/make/tools/fat16copy.py", line 773, in <module>
    root = fat(sys.argv[1]).root
  File "build/make/tools/fat16copy.py", line 469, in __init__
    "Can only handle FAT with 1 reserved sector"

Have you ever see this? Can it be old version of toolchain?
Thanks,
Snd-Raspberry

**Comment by snd-raspberry** [comment]
yes, this is an issue with build. I can build standard google AOSP source without any errors. So it seems like an issue related to your repo or build environment. Disabling check in  "build/make/tools/fat16copy.py", line 469" will  "fix" an issue, but I don't think this is generic way to fix it.

**Comment by brobwind** [comment]
I uses Ubuntu 16.04.5 LTS to build the code, and the mkfs.fat program version is '3.0.28 (2015-05-16)',  compared to yours mkfs.fat 4.1 (2017-01-24). I thinks this is the reason.

**Comment by pcans** [comment]
There is indeed an issue in the dosfstool shipped in Ubuntu 18.04.
I've been able to build successfully on Ubuntu 18.04, by rolling back dosfstool version.

Here is what I did:
```
sudo apt remove dosfstools
git clone https://github.com/dosfstools/dosfstools.git 
cd dosfstools/
git checkout v3.0.28
make
sudo apt install checkinstall
sudo checkinstall
```
Then restart your shell.
